[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200

; Non servono più i flag C++20 pesanti
build_flags = 
    -DCORE_DEBUG_LEVEL=0 ; Riduciamo il log per risparmiare RAM

lib_deps =
    ; Questa versione è la "Gold Standard" per ESP32 senza PSRAM
    schreibfaul1/ESP32-audioI2S @ 2.3.0